### PR TITLE
SpacemiT: Add X60 ACT Test Report

### PR DESCRIPTION
**Pull request by spacemit-os**
Here is the RISC-V ACT report for SpacemiT X60.

SpacemiT X60 test failed in EBREAK case. x60 was implemented based on the RISC-V-privileged version 1.12. In this version, the spec remarks that mtval is written with the virtual address on hardware breakpoints.  It is not related to the EBREAK instruction. So setting mtval to either PC or 0 is legal. However, after the issue ([EBREAK and mtval · Issue #600 · riscv/riscv-isa-manual](https://github.com/riscv/riscv-isa-manual/issues/600)), the specification was updated to require that the mtval register be filled with the current PC when executing an EBREAK instruction while still allowing the behavior of writing 0. Sail-Riscv model only supports writing current PC to mtval. It causes a discrepancy between the expected and actual values.

### CODE REVIEW

**Comment by guoguangpei-spacemit** [comment]
@allenjbaum Please feel free to review and let us know whether it is OK.

Thank you very much for your time and help.

**Comment by allenjbaum** [comment]
I'm a bit puzzled here. 
The test should write 0000_1111_1111_1111 into the regular signature, and
 should also write an encoded version of vector (12 bits) bytes of trap signature(4 bits), and mode (2bits)into the trap signature,  followed by cause (break is cause 3), followed by mtval
But the trace output:
Match  Line#    File1    File2
```
*          2 deadbeef 00000000 <-- regular signature
*          3 deadbeef 11111111
           4 000010e3 000010e3. <--vector/bytes of trapsig/mode
                                                   <-(5  also matches, and 6/7 is mcause and matches, 8/9 is  epc, which matches
*         10 deadbeef 00000044 <-10/11 is tval and doesn't match
*         11 deadbeef 00000000 <--this is 
          12 e7d4b281 e7d4b281  <- this is a canary word
```
Even if tval is different, the test should return from the trap and write the regular signature.
The order of writing is vector/leng/mode, mcause, epc, tval, regular signature.
What this signature seems to indicate the test ends prematurely (e.g. reading from tval causes a further trap.)
I think we need that explained before we can merge this.

**Comment by guoguangpei-spacemit** [comment]
When performing the check at tval, since its value is 0 instead of pc, it is not within any of the code/sig/data segments. This case ultimately proceeds to cleanup_epilog.

https://github.com/riscv-non-isa/riscv-arch-test/blob/13fb359e88f86578b9b7e4bfd080fd841348ad5f/riscv-test-suite/env/arch_test.h#L1422-L1457

So the program neither writes tval value nor returns normally from the exception handler (which also causes it to skip writing the regular signature).

**Comment by allenjbaum** [comment]
Ah, that is what is going on.
We need to fix that in the trap handler, we've never seen it before (or
maybe we had and never got a good explanation);
It's expecting to relocate tval, and it can't, because zero is a null
pointer.
This falls under the bad test waiver, qualifies.and I'm satisfied that it
We can special case this to avoid the trap, but you'll have to use a
reference mode (for this test) that has the same behavior to avoid a test
failure in the report.
In the meantime, I think this is goo to merge

**Comment by guoguangpei-spacemit** [comment]
Currently, in the commonly used reference modes, both spike and sail set tval to pc when an ebreak trap occurs. Can I use an earlier version of sail (before the commit [`ae6cb1de092e9ea727e2318d76e9b88999bbee59`](https://github.com/riscv/sail-riscv/commit/ae6cb1de092e9ea727e2318d76e9b88999bbee59)) to test this specific case independently?
Additionally, in which directory of the repository should the supplementary report for this bad test waiver be placed?

**Comment by allenjbaum** [comment]
No need to do that. You are asking for a Flawed-test test-case waiver, which is when :

If there is a demonstrable bug in the test, reference model, or tool chain that causes a test to fail, a Flawed-Test Test-Case Waiver may be requested. Flawed-Tests include cases where the reference model produces a result that differs from what the implementation  produces, and that result is one of several results that is considered correct by the rules of the ISA (e.g. WARL behavior that tests don’t support).

All waivers must be approved by a majority vote of the  appropriate ISA Committee (i.e., privileged or unprivileged) and the SW or other related non-ISA HC..

I will forward this to the unpriv ISA committee, and to software  & tools and get their approval; this should be easy (but not necessarily fast)

**Comment by allenjbaum** [comment]
I'm going to approve this pull request and merge this now. We do need to update the trap handler to take care of this case in the (near) future, but there is no need to delay the merge until then.

**Comment by allenjbaum** [comment]
the same directory as your test results.

**Comment by noionion** [comment]
So, do we still need to provide an additional report.html and .txt and initiate another pull request, which only includes the test results for ebreak.s and the version of SAIL used?

**Comment by guoguangpei-spacemit** [comment]
So, do we still need to provide an additional report.html and .txt and initiate another pull request, which only includes the test results for ebreak.s and the version of SAIL used?

**Comment by allenjbaum** [comment]
I don't think you need to provide another report.html, or report.txt; I
think a .txt explanation of the why this was a test failure
 (e.g. the spec changing to include 2 behaviors, and neither Sail nor Spike
support both) is all that is required.
I've looked through the logs, and I can see exactly what failed, and we
will be fixing it in the future to allow that behavior,
but I don't any reason to delay this self-cert until that happens.

**Pull request merged**
