### PR TITLE
StarFive: Add JH7110 ACT Test Report

### PR DESCRIPTION
**Pull request by Allen-StarFive**
Here is the RISC-V ACT report for StarFive JH7110

StarFive JH7110 has passed all the RISC-V Architecture Compatibility Tests, no any failures on it.

@allenjbaum  @jamesbeyond  @neelgala  @MarcKarasek  Please feel free to review and let us know whether it is OK.

Thank you very much for your time and help.

### CODE REVIEW

**Comment by jamesbeyond** [comment]
Hi @Allen-StarFive,

Thanks for the submission, by quick looking at your report, I noticed 2 things:
1. the supplied `gdb_isa.yaml` wasn't include the information about CSRs such as `mvendorid` `marchid` `mimpid` etc. I'd assume those readonly CSRs reset value better to be provided.
2.  in the HTML report, the comm-id and version for the ACT suite wasn't captured by the riscof framework, to get that you better let riscof framework check out the tests for you, rather than manually pre-checkout the tests
Screenshot 2023-05-05 at 01 12 28

**Comment by Allen-StarFive** [comment]
Hi @jamesbeyond 

It is my pleasure for your guide. I have relaunched the ACT test again according to your advice. 

These problems have been fixed in the new report. Please help me to check again. 

Thank you.

**Comment by jamesbeyond** [comment]
@allenjbaum @neelgala  this one is LGTM, could you please have a look, see if you have any more suggestions ?

**Comment by allenjbaum** [comment]
It's OK to leave the mimplid, marchid, and mvendor ID to be zero
It looks like Zicntr is not implemented, which is a bit strange if you're implementing SMode;
because OSes usually require a timer interrupt, and  Mtime is implemented

The MISA[23] bit is set, which indicates custom extensions
The MISA[1] bit is set, and I think it should *not* be set (the latest spec says it is reserved, even if you are implementing Zba and Zbb. That should been been caught by riscv-config, and that should be fixed.

**Comment by Allen-StarFive** [comment]
Hi @allenjbaum @jamesbeyond @neelgala @MarcKarasek 

Thank you very much for your reply. Replies for your comments are:

[1] JH7110 uses SiFive U74 core which have custom CSR instructions, so the MISA[23] bit is set, but currently SiFive does not define extension names for these directives separately.

[2] The MISA[1] bit is set, because what we're following is riscv-privileged-20211203.pdf (December 4, 2021 Released). In this document, MISA[1] bit describes as "Tentatively reserved for Bit-Manipulation extension". Rather than the lastest document (April 27, 2023 Released), MISA[1] bit describes as "Reserved".

**Comment by jamesbeyond** [comment]
> Hi @allenjbaum @jamesbeyond @neelgala @MarcKarasek
> 
> Thank you very much for your reply. Replies for your comments are:
> 
> [1] JH7110 uses SiFive U74 core which have custom CSR instructions, so the MISA[23] bit is set, but currently SiFive does not define extension names for these directives separately.
> 
> [2] The MISA[1] bit is set, because what we're following is riscv-privileged-20211203.pdf (December 4, 2021 Released). In this document, MISA[1] bit describes as "Tentatively reserved for Bit-Manipulation extension". Rather than the lastest document (April 27, 2023 Released), MISA[1] bit describes as "Reserved".

Hi @Allen-StarFive, 

Thanks for your reply please bare with us for slow progress,  Many people are busy with RISC-V Europe Summit,  so responds might not be in time. 
I understand the reason for the MISA[1] and MISA[23] bit being set, and why it is not match the latest spec. could you put those words in the waiver notes ?

@allenjbaum @neelgala  This is looks good to me,  but I'd like to hear your opinions as well.

**Comment by allenjbaum** [comment]
Do you have custom CSR instructions (something other than CSRR[W/C/S][I]),
or just custom CSRs.
Bit 23 simply means custom extensions; that is not an issue, and needs no
waiver
(if a test fails because of this, it might be because your riscv-config
YAML doesn't define the reset value?)
Bit 3 will require a Waiver.
You should file the waiver by submitting a pull request to the
arch-test-reports repo with a couple of sentences explains what the errata,
the reason for it, and say it is a low impact errata and you would like to
get a waiver. This should not have problems getting waived.

**Comment by Allen-StarFive** [comment]
Hi @jamesbeyond @allenjbaum @neelgala

**Comment by Allen-StarFive** [comment]
Hi @jamesbeyond @allenjbaum @neelgala 

I have relaunched the ACT test again according to your advice. 

I have changed the value of MISA[23] bit to 0 because custom CSR instructions do not affect test results, and added a waiver note in JH7110-2023-06-09-notes.txt to explain why MISA[1] bit is set.

Thank you.

**Comment by allenjbaum** [comment]
You have custom extensions, so the X bit should remain set. I don't
actually know if anything bad happens if you have custom extensions but
misa.X is 0,
but there might be a toolchain issue down the line that might complain.
If there is a test that fails because of misa.X=1 - then the test is buggy,
not your implementation, and we need to fix it, not you.
The only issue is the MISA[1] bit.

**Comment by Allen-StarFive** [comment]
Hi @allenjbaum @jamesbeyond @neelgala 

Thanks for your guidance.
I have relaunched the ACT test again, and remained the X bit set.

**Comment by allenjbaum** [comment]
I am still confused by your explanation of the EBREAK failure, ad your use
of the term HW-breakpoint vs. SW-breakpoint.
A HW breakpoint is when HW detects that some instruction is being executed.
A SW breakpoint is when an EBREAK instruction replaces the instruction you
want to breakpoint on,
You say that HW breakpoints were used in the C910 because it has a
proprietary debugging module.
Does that mean that the EBREAK instruction running on the C910does not trap
and log the exception (EPC, CAUSE, TVAL) as mandated in the privileged spec?
Or does the actual C910 do the right thing, but the testbench intercepts it?
Can you explain how it is not compatible with the ACT framework, yet it is
compatible with the RISC-V privileged architecture?
OR, are you instead saying that you have a custom privileged architecture
(because EBREAK does something different) - which is OK if you want RVI
compatibility, but not RVA compatibility.

failure_reason: When running the ACT suite, ebreak instruction served as
SW-breakpoint for putting the target in stop mode, enabling ACT to examine
the targets.
Because of this, ebreak test is running, the target behaviour will confuse
the ACT so it failed.
SW-breakpoints rather than HW-breakpoints were used in C910 when running
ACT because C910 has a proprietary debugging module,
HW-breakpoint is not compatible with the ACT framework.

**Comment by Allen-StarFive** [comment]
@allenjbaum 
Sorry, I don't understand the relationship between these questions of C910 and JH7110. 
Do you have any comments for my last updates on JH7110? 
Thank you sincerely.

**Comment by allenjbaum** [comment]
My apologies; I don't know how I accessed the C910 report & can't duplicate
it. The JH7110 report is fine.

**Comment by Allen-StarFive** [comment]
@allenjbaum @jamesbeyond 
Thanks for your guide and help sincerely.

**Pull request merged**
