### PR TITLE
T-Head: Xuantie C908 ACT Report 2023-02-24

### PR DESCRIPTION
**Pull request by jamesbeyond**
This is the first RISC-V ACT report from T-Head Xuantie C908

T-Head Xuantie C908 had passed all required the RISC-V Architecture Compatibility Tests ! 🍾 

We would like to share this great news with you and contribute our efforts for help ACT flow evolving .
@allenjbaum Please have a look and let us know what is you thoughts about this report.

### CODE REVIEW

**Review by billmcspadden-riscv — APPROVED** [review]
All of my requested changes (which were made via email and not through github),  appear to be addressed.  

This PR looks ready to merge.

**Review by cetola — APPROVED** [review]
This looks good to me. Suggest we merge.

**Comment by cetola** [comment]
@allenjbaum Any reason we should not merge these test reports for the C908?

**Review by allenjbaum — COMMENTED** [review]
This has all the information that is required for self certification.
However, the YAML lists (mostly) the features that we currently have tests for (except for A-extension, which it lists, but we have no tests for), but not the features they implement that we don't have tests for.
XuanTie C908 supports vector, but doesn't seem to support the mstatus.VS field, which seems odd. (I think that's a RISCV-config bug that defaults it - and it's not something we test yet).
sstatus  and satp are listed as not implemented - but I don't think that is possible if XuanTie C908 supports SV39/48, as their press release indicates.
It also says that supports the CMO base, and Svinval extension, but those aren't listed in the ISA string, along with Svnapot and Svpbmt (which it "holds up" - I don't know what that means - a custom impelmentation?) I'm concerned that what they claim to support is only a subset of what they actually support, and this wouldn't meet RVA22 profile as it stands (I think....) which their press release indicates they support.
It also doesn't support interrupt delegation, so all interrupts are handled in M-mode, 
and doesn't implement virtual memory, which also seems odd for an implementation that has M,S, and U modes (satp isn't implemented)
IT also doesn't implement mvendorID, mimpID, or marchID, which is also odd for a vendor supplying multiple implementations. It isn't required to have these - but I mention it because I want to make sure that their YAML matches what they are really implementing, for their sake. 
I think misa is defined incorrectly. The mask field is 0x20112D, and the value field is 0; this is reversed. I'm not sure it is actually legal, and it implies that these extensions can be dynamically enabled and disabled - which is very unlikely.

**Comment by allenjbaum** [comment]
Given that the 
 - YAML is for an M-only implementation, with vector support and A-extension support that we can't tests
 -  it passes all the tests that we currently define,
 - the report contains all the information that the policy requires, I think we can (must) accept the PR

**Pull request merged**
